version: "3"
services:
  budgeting-app-backend:
    container_name: ps4-budgeting-app-backend
    restart: always
    build: .
    ports:
      - "9095:9090"
    environment:
      POSTGRES_HOST: postgresdb
    depends_on:
      - postgresdb
  postgresdb:
    container_name: postgresdb
    image: postgres
    volumes:
      -  /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin123
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
      - "9096:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    depends_on:
      - postgresdb