name: Automated Deployment

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Back end
      run: docker compose build budgeting-app-backend
    - name: Start database, pgadmin, and backend
      run: docker compose up -d
