name: Automated Deployment

on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Back end
      run: docker compose build budgeting-app-backend
    - name: Start database, pgadmin, and backend
      run: docker compose up -d
